import type { Metadata } from "next";
import { Nunito } from 'next/font/google';
import "./globals.css";

const nunito = Nunito({
  subsets: ['latin'],          // Carga solo el subconjunto que necesitas
  weight: ['400', '600', '700', '800', '900'], // Los pesos que usas
  display: 'swap',             // Para mejorar el rendimiento
  variable: '--font-nunito',   // Crea una variable CSS para usarla en Tailwind
});

export const metadata: Metadata = {
  title: "Amauta",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/favicon/favicon.ico', sizes: 'any' },
      { url: '/favicon/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon/favicon-96x96.png', sizes: '96x96', type: 'image/png' },
    ],
    apple: [
      { url: '/favicon/apple-touch-icon.png', sizes: '180x180' },
    ],
  },
  manifest: '/favicon/site.webmanifest',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"  suppressHydrationWarning>{children}</body>
    </html>
  );
}
